SELECT I_ID_LDARDRAW "id",
	I_ID_LDAR "LDARId",
	I_DRAWING_SHEET "idDrawingSheet",
	I_LDAR_DRAWDISPO "drawingNumber",
	I_LDAR_ADCNDCN "adcn",
	I_LDAR_DRAWSHEET "drawingSheet",
	I_ENTRY "entry"
FROM DBAPDM.TMLDARDRAW