SELECT I_ID_LDARAPRV "id",
	B.I_ID_LDAR "LDARId",
	B.I_LDAR "number",
	C.I_ID_LDARAPRVTYPE "typeCode",
	C.E_LDAR_APRVTYPE "type",
	I_LDAR_APRV "nik",
	E.N_ROLE "role",
	E_LDAR_APRVRMK "remark",
	N_LDAR_FILEAPRV "fileName"
FROM DBAPDM.TMLDARAPRV A
	INNER JOIN DBAPDM.TMLDAR B ON A.I_ID_LDAR = B.I_ID_LDAR
	INNER JOIN DBAPDM.TRLDARAPRVTYPE C ON A.I_ID_LDARAPRVTYPE = C.I_ID_LDARAPRVTYPE
	INNER JOIN DBAPDM.TRLDARUSERROLE D ON A.I_LDAR_APRV = D.I_EMP 
	INNER JOIN DBAPDM.TRLDARROLE E ON D.I_ID_LDARROLE = E.I_ID_LDARROLE

