SELECT I_ID_LDARAPRV "id",
	I_ID_LDAR "LDARId",
	B.I_ID_LDARAPRVTYPE "typeCode",
	B.E_LDAR_APRVTYPE "type",
	I_LDAR_APRV "nik",
	E_LDAR_APRVRMK "remark",
	N_LDAR_FILEAPRV "fileName"
FROM DBAPDM.TMLDARAPRV A
	INNER JOIN DBAPDM.TRLDARAPRVTYPE B ON A.I_ID_LDARAPRVTYPE = B.I_ID_LDARAPRVTYPE