stages:
  - init
  - staging
  - deploy

cache:
  paths:
    - node_modules/

init:
  stage: init
  script:
    - npm install
  only:
    - development

deploy_dev:
    stage: deploy
    script:
      - tar --exclude='./.git' --exclude='*.yml' --exclude='.gitignore' -zcvf ~/temp/ldar-be/DEV/ldar-be.tgz .
      - tar -xzvf ~/temp/ldar-be/DEV/ldar-be.tgz -C ~/temp/ldar-be/DEV
      - rm -rf ~/temp/ldar-be/DEV/ldar-be.tgz
      - scp -r ~/temp/ldar-be/DEV/. $SERVER_DEV:/web-source/ldar-be
      - rm -rf ~/temp/ldar-be/DEV/*
      - ssh $SERVER_DEV "/usr/local/node/nodejs/bin/pm2 restart ldar_backend"
      - echo "Deploy server Development berhasil"
    only:
      - development
