UPDATE DBAPDM.TMLDAR
SET I_LDAR_TOSPV = :updateUser,
	N_LDAR_TOSPV = :EDMName,
	D_LDAR_TOSPV = CURRENT_DATE,
	I_LDAR_ATTENTION = :PENik,
	N_LDAR_ATTENTION = :PEName,
	N_LDAR_GRP = :groupAta,
	I_UPDATE = :updateUser,
	D_UPDATE = CURRENT_DATE
WHERE I_ID_LDAR = :id