SELECT
	B.I_ID_LDARMENU "id",
	N_LDAR_MENU "name",
	I_ID_PARENT "parentId",
	N_LDAR_URLMENU "url",
	C_LDAR_SORTMENU "code",
	N_LDAR_ICONMENU "icon",
	C_LDAR_ACTMENU "status"
FROM
	DBAPDM.TRLDARROLEMENU A
INNER JOIN DBAPDM.TRLDARMENU B
ON
	A.I_ID_LDARMENU = B.I_ID_LDARMENU
